### ISSUE TITLE
HTML email support

### ISSUE THREAD

**Issue by mrchrisadams** [reclosedev/lathermail#3]
Hi there,

Thanks for creating lathermail! I came across when looking for a Python 3 based equivalent to maildump.

Do you have any plans to support showing the rendered HTML in an email, like you show the plain text? This is one feature I used all the time in maildump, and I'm not sure how to replicate this.

I've had a look through the source code, and I'd be up for creating a pull request and having a go at implementing this myself,  but I've never used angularjs, nor flask.

Can you point me at the files I might need to change if I wanted to do this?

I'm assuming these two are the areas I ought to be looking at if I want to see how the plain text is rendered on the page:

https://github.com/reclosedev/lathermail/blob/master/lathermail/mail.py#L43
https://github.com/reclosedev/lathermail/blob/master/lathermail/web/static/index.html#L107

Would it be a case of adding another tab, and adding a 'html' key to the dict yielded in `iter_parts`?

Thanks

**Comment by reclosedev** [comment]
Thanks for you interest!

I've wanted to answer you questions, but added support for HTML messages in API and UI while looking at code :)

Version 0.3.0 is published to PyPI.

diff: https://github.com/reclosedev/lathermail/compare/27ef8c563967443aff8216c2c0580c4715782f98...ae08ac47cb80689ae0af6049a9f893d5874aa0ea
related: #2
